In [3]:
import numpy as np
from PIL import Image
from mss import mss
import cv2

BOX_MY_SCREEN = {'left': 410, 'top': 330,
                 'width': 1025 - 410, 'height': 480 - 330}


def get_box_monitors():
    return mss().monitors


def showImageScreenShoot(box_frame=BOX_MY_SCREEN):
    _img = mss().grab(box_frame)
    _img_final = Image.frombytes('RGB', _img.size, _img.bgra, 'raw', 'BGRX')
    _img_final.show()


def show_image_screen_shoot_by_path(path: str):
    _img_final = Image.open(path)
    _img_final.show()    
    
def convert_img_to_array_3(img=None):
    if img is None:
        img=BOX_MY_SCREEN
        _img = mss().grab(img)        
    elif type(img) is str:
        _img = Image.open(img)    
    _np_array = np.array(_img)
    return _np_array, _np_array[:, :, :3]


def get_sum_array_img(box_frame=BOX_MY_SCREEN):
    img = np.array(mss().grab(box_frame))[:,:,:3]
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    return gray.sum()

def get_sum_array_img_by_path(box_frame=BOX_MY_SCREEN):
    img = np.array(mss().grab(box_frame))[:,:,:3]
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    return gray.sum()

In [54]:
a,b=convert_img_to_array_3('dingo.png')
gray = cv2.cvtColor(b, cv2.COLOR_BGR2GRAY)
display(gray.sum())

280833

In [ ]:
display(convert_np_array_to_array_3())

In [6]:
display(get_sum_array_img())

8186428

In [21]:
Image.fromar.show()

In [72]:
print('a\tb\tc\td\te')
for i in range(0, 1000):
    print(i, sep='',end='\r',flush=True)

a	b	c	d	e


In [77]:
import os
os.path.join('media', 'dingo.png')

'media/dingo.png'

In [108]:
dino_template = cv2.imread('media/dingo.png', 1)[:,:,:3]
display(dino_template)
Image.fromarray(dino_template).show()

array([[[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       ...,

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[247, 247, 247],
        [247, 247, 247],
        [247, 247, 247],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]]

In [92]:
# Get width and height of image

width_image, height_image = cv2.imread('media/only_dingo.png', 0).shape[::-1]
display(width_image, height_image)

681

194

In [93]:
# Convert image màu sang image xám

image = np.array(Image.open('media/monitor_laptop.png'))[:,:,:3]
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
print(gray_image)
Image.fromarray(gray_image).show()

[[69 69 69 ... 40 40 40]
 [69 69 69 ... 40 40 40]
 [69 69 69 ... 40 40 40]
 ...
 [11 11 11 ... 11 10  9]
 [11 11 11 ... 11 11 10]
 [11 11 11 ... 11 10 11]]


In [10]:
# 
import os

dino_template = cv2.imread('media/dino.png',0)
w, h = dino_template.shape[::-1]
landscape_template = cv2.imread(os.path.join('media/only_dingo.png'), 0)
lw, lh = landscape_template.shape[::-1]


image = np.array(Image.open('media/monitor_laptop.png'))[:,:,:3]
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
res = cv2.matchTemplate(gray_image, dino_template, cv2.TM_CCOEFF_NORMED)
# display(res)
loc = np.where(res >= 0.7)
monitor=mss().monitors[1]
if len(loc[0]):
    pt = next(iter(zip(*loc[::-1])))
    landscape = dict(monitor, height=lh, left=pt[0], top=pt[1] - lh + h, width=lw)
display(landscape)

{'left': 432, 'top': 333, 'width': 610, 'height': 142}

In [1]:
def compute_region_of_interest(landscape):
    # tu thong tin ve landscape, ta lay ra duoc 1 vung chua day du cac vat the can
    # xem xet, nhung lai nho hon landscape (do do giam duoc khoi luong tinh toan)
    ground_height = 12
    y1 = landscape['height'] - 44
    y2 = landscape['height'] - ground_height
    x1 = 44 + 24
    x2 = landscape['width'] - 1
    return x1, x2, y1, y2
compute_region_of_interest({'left': 433, 'top': 272, 'width': 681, 'height': 194})

(68, 680, 150, 182)

In [19]:
a=1
if a:
    print(68, 609, 98, 130)

68 609 98 130


In [26]:
import time
time.time()


1616746251.6206641

In [27]:
a=[]
display(a)
a.append(11)
display(a[0])
a.append(12)
display(a[0])
a.append(13)

display(a[0])


[]

11

11

11